// ═══════════════════════════════════════════════════════════════
//  CASH COLLECTION MEASURES
// ═══════════════════════════════════════════════════════════════
// NOTE: These measures require a [payments_collected_eur] column
// in fact_ar_performance. If not yet available, derive as:
//   payments_collected = AR (prev month) - AR (current) + new invoices
// Add that column in Power Query once the source data includes it.

Payments Collected =
SUM(fact_ar_performance[payments_collected_eur])

Payments Collected PM =
CALCULATE([Payments Collected], PREVIOUSMONTH(dim_date[date]))

Payments MoM Change =
[Payments Collected] - [Payments Collected PM]

Payments MoM Change % =
DIVIDE([Payments MoM Change], [Payments Collected PM])

// Collection Rate = payments collected vs. opening overdue balance
Collection Rate =
DIVIDE([Payments Collected], [Overdue Amount PM])

Collection Rate Label =
FORMAT([Collection Rate], "0.0%")
