// ═══════════════════════════════════════════════════════════════
//  OVERDUE & AGING MEASURES
// ═══════════════════════════════════════════════════════════════

// ── Totals ────────────────────────────────────────────────────

AR Total =
SUM(fact_ar_performance[ar_eur])

Overdue Amount =
SUM(fact_ar_performance[overdue_eur])

GT60 Amount =
SUM(fact_ar_performance[gt60_eur])

GT90 Amount =
SUM(fact_ar_performance[gt90_eur])


// ── Percentage of AR ──────────────────────────────────────────

Overdue % =
DIVIDE([Overdue Amount], [AR Total])

GT60 % =
DIVIDE([GT60 Amount], [AR Total])

GT90 % =
DIVIDE([GT90 Amount], [AR Total])


// ── Prior month comparisons ───────────────────────────────────

Overdue Amount PM =
CALCULATE([Overdue Amount], PREVIOUSMONTH(dim_date[date]))

Overdue % PM =
CALCULATE([Overdue %], PREVIOUSMONTH(dim_date[date]))

GT90 Amount PM =
CALCULATE([GT90 Amount], PREVIOUSMONTH(dim_date[date]))


// ── MoM changes ──────────────────────────────────────────────

Overdue MoM Change EUR =
[Overdue Amount] - [Overdue Amount PM]

Overdue MoM Change Pct =
[Overdue %] - [Overdue % PM]

GT90 MoM Change EUR =
[GT90 Amount] - [GT90 Amount PM]


// ── Top contributor rank by overdue ──────────────────────────

Overdue Impact Rank =
RANKX(
    ALL(fact_ar_performance[customer]),
    [Overdue Amount],
    ,
    DESC,
    DENSE
)


// ── KPI Card labels (formatted) ───────────────────────────────

Overdue % Label =
FORMAT([Overdue %], "0.0%")
& IF(
    NOT ISBLANK([Overdue % PM]),
    " (" & IF([Overdue MoM Change Pct] >= 0, "+", "")
        & FORMAT([Overdue MoM Change Pct], "0.0pp") & " MoM)",
    ""
)

GT90 % Label =
FORMAT([GT90 %], "0.0%")
& IF(
    NOT ISBLANK([GT90 Amount PM]),
    " (" & IF([GT90 MoM Change EUR] >= 0, "+", "")
        & FORMAT([GT90 MoM Change EUR] / 1000000, "#,##0.0M €") & " MoM)",
    ""
)
